version: "3.5"

services:

  php: #container
    build:
      context: php #directory
    ports:
      - "8000:80"
    volumes:
      -  ./app:/var/www/html #root directory

  mysqldb:
    image: mysql:latest
    ports:
      - "3307:3307"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: 0000
    volumes:
      - ./mysqldatabase:/var/lib/mysql
      - ./app/init.sql:/data/application/init.sql
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image:   phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysqldb
      PMA_USER: user
      PMA_PASSWORD: 0000
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: mysqldatabase
