version: "3.5"

services:

  php-apache: #container
    build: './php-apache' #directory
    ports:
      - "8000:80"
    volumes:
      - ./public_html:/home/public_html #root directory

  nginx: #container
    build: './nginx'
    ports:
      - "8081:80"
    volumes:
      - ./nginx-public_html:/home/public_html
    depends_on:
      - php-apache

  mysqldb:
    build:
      context: db_conf
    ports:
      - "3307:3307"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: 0000
    volumes:
      - ./mysqldatabase:/var/lib/mysql

  phpmyadmin:
    image:   phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysqldb
      PMA_USER: admin
      PMA_PASSWORD: 0000
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: mysqldatabase
